[build]
  command = "pip install -r requirements.txt && gunicorn app:app"
  publish = "/"

[[plugins]]
  package = "@netlify/plugin-python"
  [plugins.inputs]
    pythonVersion = "3.9"

[functions]
  directory = "functions/"